import { afterEach, describe, expect, it, vi } from 'vitest'
import { USER_ROLE_OPTIONS } from '@/types/member-profile'
import {
  applySelfSaveScope,
  buildCarrierOnlyApiSavePayload,
  buildCarrierOnlySavePayload,
  canSaveCarrierInfo,
  logCarrierSaveDebug,
  validateBootstrapCarrierSaveRoles,
  buildMemberProfileSavePayloadWithoutCarrier,
  buildSelfMemberSavePayload,
  canSelfEditRoles,
  isAnySaveInFlight,
  memberEditCardTitle,
  memberEditSaveDisabled,
  memberEditSaveButtonLabel,
  shouldShowMemberSaveInCardHeader,
  resolvePersistedRosterId,
  shouldShowBootstrapProfilePrompt,
  shouldShowOwnerBootstrapSetupCard,
  needsPrimaryOwnerBootstrap,
  hasExistingTeamMembership,
  memberProfileFromLinkedRoster,
  resolveActorProfile,
  clampSelfSaveRolesFromTeamContext,
  resolveSelfSaveOrganizationId,
  isOwnerOperatorSelected,
  applyOwnerOperatorRoles,
  prepareBootstrapFormForSave,
  normalizeBootstrapSelfRoles,
  isValidMemberProfileUserRolesCombination,
  validateBootstrapSelfSave,
  validateBootstrapCarrierOnlySave,
  validateBootstrapOptionalEmail,
  validateBootstrapOptionalPhone,
  validateBootstrapEmail,
  BOOTSTRAP_MAX_PHONE_LENGTH,
  BOOTSTRAP_MAX_EMAIL_LENGTH,
  getOwnerBootstrapSetupCardTitle,
  getOwnerBootstrapSetupCardSubtitle,
  getOwnerBootstrapOwnerOperatorHint,
  getOwnerBootstrapSaveButtonLabel,
  carrierFieldsDiffer,
  emptyMemberProfileForm,
  formatCarrierNameSummary,
  formatCarrierSummaryDisplay,
  hasCarrierData,
  memberProfileFromRow,
  memberProfileToUpsertPayload,
  memberProfileToUpsertPayloadWithoutCarrier,
  normalizeCdlState,
  prepareMemberProfileSave,
  resetCarrierFieldsInForm,
  resolveCarrierDataSource,
  shouldBootstrapOrganization,
  shouldShowCarrierForm,
  shouldShowCarrierInformationCard,
  shouldShowEditMyProfileOnLanding,
  shouldShowLandingProfileView,
  shouldShowMemberEditCard,
  shouldShowUserRolesSection,
  shouldShowOwnerAdminBadge,
  shouldShowAssignedRoleBadges,
  getLandingAssignedRoles,
  getMemberEditCardSubtitle,
  getTeamMemberRolesHelperText,
  getTeamSectionCarrierHelperText,
  CARRIER_SAVE_FORBIDDEN_MESSAGE,
  ensureBootstrapOwnerAdminRoles,
  isUserRolesReadOnlyOnProfile,
  getUserRolesSectionHelperText,
  USER_ROLES_HELPER_BOOTSTRAP,
  USER_ROLES_HELPER_MANAGED_BY_OWNER,
  USER_ROLES_HELPER_LANDING_READONLY,
  USER_ROLES_SAVE_WITH_PROFILE_HINT,
  shouldShowTeamSectionCarrierBlock,
  shouldShowTeamSectionCarrierDetails,
  shouldUseCarrierSummaryMode,
  shouldUseTeamMemberCarrierSummary,
  teamMemberProfileFromRow,
  teamMemberProfileToPayload,
  assertAssignableTeamMemberRoles,
  buildTeamMemberChildRosterPayload,
  pickCarrierInheritanceSource,
  rejectNonBootstrapOwnerRoles,
  NON_BOOTSTRAP_OWNER_ROLE_MESSAGE,
  NON_ASSIGNABLE_TEAM_ROLE_MESSAGE,
  TEAM_MEMBER_ROLES_REQUIRED_MESSAGE,
  validateUserRoles,
  generateOrganizationId,
} from './member-profile'

describe('owner bootstrap helpers (MoHeavy AI rebrand)', () => {
  it('exposes welcome copy and save label for bootstrap card', () => {
    expect(getOwnerBootstrapSetupCardTitle()).toBe('Welcome to MoHeavy AI')
    expect(getOwnerBootstrapSetupCardSubtitle()).toContain('account Owner')
    expect(getOwnerBootstrapOwnerOperatorHint()).toContain('Team Roster')
    expect(getOwnerBootstrapSaveButtonLabel(false)).toBe('Save & continue')
    expect(getOwnerBootstrapSaveButtonLabel(true)).toBe('Saving...')
  })
})
